.TH "tool" "1" "" "" ""
.SH NAME
tool \- Snapshot tool
.SH SYNOPSIS
.B tool
.RI " [OPTIONS] <command>"
.SH DESCRIPTION
.PP
Snapshot tool
.SH COMMANDS
.TP
.B run
Run target
.SH OPTIONS
.TP
.B \-\-verbose, \-v
type: bool, default: false
Verbose output
.TP
.B \-\-color auto|always|never
type: choice, value: auto|always|never, default: "auto"
When to colorize output
