.TH "TOOL" "1" "1970-01-01" "" ""
.SH NAME
tool \- Snapshot tool
.SH SYNOPSIS
.B tool
.RI " [OPTIONS] <command>"
.SH DESCRIPTION
Snapshot tool
.SH COMMANDS
.TP
.B run, r
Run target
.SH OPTIONS
.TP
.B \-\-verbose, \-v
type: bool, default: false
Verbose output
.TP
.B \-\-debug, \-d
type: count, repeatable
Increase debug verbosity (repeatable)
.TP
.B \-\-color auto|always|never
type: choice, value: auto|always|never, default: "auto"
When to colorize output
.SH FLAG GROUPS
.TP
.B display
at least one required: \-\-verbose, \-\-color
Choose at least one display control.
